//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Project/Resources/InputActionAssets/Com2VerseAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Com2VerseAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Com2VerseAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Com2VerseAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c8a80cd7-dee9-42cd-a41d-fd72cfb747b1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bb8ded4d-bf74-43ef-9ef5-8af64e3111fc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b6785c2d-148d-4676-b62a-d430b83fae45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""374427c5-305b-45f1-9f87-5acab44f1d17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""d22062d1-8a60-41fd-8174-d2e4842c13c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Value"",
                    ""id"": ""47d45b00-bed8-4892-b295-46df53b4dcf9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""26e68a0f-1219-4ef6-94aa-9843ad1ae2a9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Chat"",
                    ""type"": ""Button"",
                    ""id"": ""b6bf33b1-2362-40d0-a56f-9232f216a099"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""519f8322-982c-4819-8c3d-1d5b85f9d6a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2f13bc41-af2f-4bba-afb1-4458fec54620"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut3"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5c1b302c-2bdb-454e-823d-6bcb8a53465f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut4"",
                    ""type"": ""PassThrough"",
                    ""id"": ""91797d1e-f8a2-44cd-9785-518f83b03e2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut5"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4fd5fafa-2d95-47c9-8047-c20a4c6fcea9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut6"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ce6c72fd-1ba2-481e-9ac9-59147e34c176"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut7"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bcb8553d-2621-4e37-951b-49a23fbe20b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut8"",
                    ""type"": ""PassThrough"",
                    ""id"": ""03e0f776-024d-4391-8e6d-71f6bad134fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut9"",
                    ""type"": ""PassThrough"",
                    ""id"": ""34cf93d5-2108-45af-816b-24a1c16d7158"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shortcut0"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b51a81a3-b9ef-4e7f-95e8-cb26bc5122b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Emotion"",
                    ""type"": ""Button"",
                    ""id"": ""03616c6f-3aa3-46c8-b694-0a2a526c94c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ctrl"",
                    ""type"": ""Button"",
                    ""id"": ""f4943398-0a2e-4f47-8d5d-a987d7c525a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Minimap"",
                    ""type"": ""Button"",
                    ""id"": ""438d62b4-708f-4f95-8732-f65d347275f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""979b437f-3629-4d6f-9173-548fc8c0a607"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7c283a20-c294-447b-8a9b-5ae62b5222ea"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d78c6a85-24a0-4feb-bfdf-ac1c02d94fea"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""31b99474-27fb-4d6e-bbca-90508ad4e85f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1244a5d7-b40e-4bf0-93ec-e9a1e41aea0b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f25bd7ae-9d78-41f6-9465-a582737a814b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0300fb34-bf43-482c-b858-3d3ddb0bca26"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""184c0083-d496-49f3-b9da-3dee9e9e0d32"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""017f83b7-4d15-43c6-8614-855b6114f9aa"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1a41f60-954b-4377-af6f-bbaa544c27df"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c4861215-13c4-43c8-a071-35ca98cc2f54"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2ba5e72f-2c74-4665-a532-07b811695153"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a5fe0d0b-b5ca-4c44-823e-eaa8472e92e3"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),ScaleVector2(x=0.1,y=0.1)"",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""15b5afe7-e086-4c19-8964-cb60b13c4457"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Invert,Scale(factor=0.0083)"",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67672b96-be1d-4e7f-b500-de5bc85009ef"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""163932e6-f52b-407a-9263-520e60bb5b0c"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4729d99c-53bf-4cc2-beb0-c52393d4f1bf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bc54202-b0cd-416f-8ef6-5c16426ed528"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Chat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57dafaf4-46db-4623-9456-56b1f120b035"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""329a0314-07b3-48ee-9ca7-af559b01eed0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e7d973b-d1a0-42e1-aa1e-b85b5f2ee235"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08aeb8ee-da0b-4519-bc84-4685d626fce7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee402930-d23a-49fe-b191-770f116ce411"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04f16b07-92aa-456e-8a49-a673c73cc423"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""753ccb8e-7135-49aa-8679-1ffc9882bb87"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b7ddfee-a5f2-41f8-987e-d0084fd0b546"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac35d200-bc8c-49bb-a01c-f6cb8dddfed8"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""454d8eb8-73f2-4a3a-9c1d-910869891962"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shortcut0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dec14c86-4512-4966-bdcb-37985bb6d8b9"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Emotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef7f4933-e30e-45fb-83d0-d6cfecd4cca1"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Ctrl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dba4ac7e-65ab-4df0-997b-cb33cc66ab18"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Minimap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d32dcbad-d501-4d73-b8b8-86750e9551c0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""731da657-f425-4bef-900b-25bd73f13244"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""a6b216aa-1e45-43c0-b622-0cd66afd7132"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""5f0bf05e-e9d1-44fa-8168-b943a99fd056"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDrag"",
                    ""type"": ""Value"",
                    ""id"": ""3679f127-86c9-4d5c-9fec-681630fbbad6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightDrag"",
                    ""type"": ""Value"",
                    ""id"": ""a3d7f6cc-f282-494f-a069-7ea501a0ce90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Minimap"",
                    ""type"": ""Button"",
                    ""id"": ""079bd24d-cb6f-4543-9b84-04cf7e53762e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""03b27d58-58c3-4469-b276-45ba11f27661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""983b800a-7b4a-422c-804d-240e7cafe9da"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""150a0f10-5f9b-433c-9d5d-de99b1f85707"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Invert,Scale(factor=0.0083)"",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d7a10715-df7d-49e0-8320-2de887fb23ec"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDrag"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7712d056-66db-4213-9596-e466dbb736ad"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""RightDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6ead0a8e-214f-40fa-92bc-d34b85c8f68c"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),ScaleVector2(x=0.1,y=0.1)"",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""RightDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ac33cd04-065a-40be-9f65-bffdcd236f06"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDrag"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""473e0d4e-7e79-4a80-b840-93a0312ec2d8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LeftDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""33ba833c-4fc1-41d5-b74b-d9f1b2eec29f"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),ScaleVector2(x=0.1,y=0.1)"",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LeftDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""97428ae9-5be6-4d93-a76c-ce6670e8cc18"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Minimap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54e8aebd-1e37-4d71-b7d9-c6f79e74738e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WebViewUI"",
            ""id"": ""efdbe737-d26f-4377-bdac-b02dfcf2ce03"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""0b2c07cf-fd49-437e-aa28-d3b460a1a768"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4d93b008-c283-4493-843f-069111011685"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WaitingBlock"",
            ""id"": ""5382be5c-3dae-4d47-aebb-5a162ae30cc5"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Interaction = m_Player.FindAction("Interaction", throwIfNotFound: true);
        m_Player_Drag = m_Player.FindAction("Drag", throwIfNotFound: true);
        m_Player_Zoom = m_Player.FindAction("Zoom", throwIfNotFound: true);
        m_Player_Chat = m_Player.FindAction("Chat", throwIfNotFound: true);
        m_Player_Shortcut1 = m_Player.FindAction("Shortcut1", throwIfNotFound: true);
        m_Player_Shortcut2 = m_Player.FindAction("Shortcut2", throwIfNotFound: true);
        m_Player_Shortcut3 = m_Player.FindAction("Shortcut3", throwIfNotFound: true);
        m_Player_Shortcut4 = m_Player.FindAction("Shortcut4", throwIfNotFound: true);
        m_Player_Shortcut5 = m_Player.FindAction("Shortcut5", throwIfNotFound: true);
        m_Player_Shortcut6 = m_Player.FindAction("Shortcut6", throwIfNotFound: true);
        m_Player_Shortcut7 = m_Player.FindAction("Shortcut7", throwIfNotFound: true);
        m_Player_Shortcut8 = m_Player.FindAction("Shortcut8", throwIfNotFound: true);
        m_Player_Shortcut9 = m_Player.FindAction("Shortcut9", throwIfNotFound: true);
        m_Player_Shortcut0 = m_Player.FindAction("Shortcut0", throwIfNotFound: true);
        m_Player_Emotion = m_Player.FindAction("Emotion", throwIfNotFound: true);
        m_Player_Ctrl = m_Player.FindAction("Ctrl", throwIfNotFound: true);
        m_Player_Minimap = m_Player.FindAction("Minimap", throwIfNotFound: true);
        m_Player_Escape = m_Player.FindAction("Escape", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Confirm = m_UI.FindAction("Confirm", throwIfNotFound: true);
        m_UI_Zoom = m_UI.FindAction("Zoom", throwIfNotFound: true);
        m_UI_LeftDrag = m_UI.FindAction("LeftDrag", throwIfNotFound: true);
        m_UI_RightDrag = m_UI.FindAction("RightDrag", throwIfNotFound: true);
        m_UI_Minimap = m_UI.FindAction("Minimap", throwIfNotFound: true);
        m_UI_Escape = m_UI.FindAction("Escape", throwIfNotFound: true);
        // WebViewUI
        m_WebViewUI = asset.FindActionMap("WebViewUI", throwIfNotFound: true);
        m_WebViewUI_Confirm = m_WebViewUI.FindAction("Confirm", throwIfNotFound: true);
        // WaitingBlock
        m_WaitingBlock = asset.FindActionMap("WaitingBlock", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Interaction;
    private readonly InputAction m_Player_Drag;
    private readonly InputAction m_Player_Zoom;
    private readonly InputAction m_Player_Chat;
    private readonly InputAction m_Player_Shortcut1;
    private readonly InputAction m_Player_Shortcut2;
    private readonly InputAction m_Player_Shortcut3;
    private readonly InputAction m_Player_Shortcut4;
    private readonly InputAction m_Player_Shortcut5;
    private readonly InputAction m_Player_Shortcut6;
    private readonly InputAction m_Player_Shortcut7;
    private readonly InputAction m_Player_Shortcut8;
    private readonly InputAction m_Player_Shortcut9;
    private readonly InputAction m_Player_Shortcut0;
    private readonly InputAction m_Player_Emotion;
    private readonly InputAction m_Player_Ctrl;
    private readonly InputAction m_Player_Minimap;
    private readonly InputAction m_Player_Escape;
    public struct PlayerActions
    {
        private @Com2VerseAction m_Wrapper;
        public PlayerActions(@Com2VerseAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Interaction => m_Wrapper.m_Player_Interaction;
        public InputAction @Drag => m_Wrapper.m_Player_Drag;
        public InputAction @Zoom => m_Wrapper.m_Player_Zoom;
        public InputAction @Chat => m_Wrapper.m_Player_Chat;
        public InputAction @Shortcut1 => m_Wrapper.m_Player_Shortcut1;
        public InputAction @Shortcut2 => m_Wrapper.m_Player_Shortcut2;
        public InputAction @Shortcut3 => m_Wrapper.m_Player_Shortcut3;
        public InputAction @Shortcut4 => m_Wrapper.m_Player_Shortcut4;
        public InputAction @Shortcut5 => m_Wrapper.m_Player_Shortcut5;
        public InputAction @Shortcut6 => m_Wrapper.m_Player_Shortcut6;
        public InputAction @Shortcut7 => m_Wrapper.m_Player_Shortcut7;
        public InputAction @Shortcut8 => m_Wrapper.m_Player_Shortcut8;
        public InputAction @Shortcut9 => m_Wrapper.m_Player_Shortcut9;
        public InputAction @Shortcut0 => m_Wrapper.m_Player_Shortcut0;
        public InputAction @Emotion => m_Wrapper.m_Player_Emotion;
        public InputAction @Ctrl => m_Wrapper.m_Player_Ctrl;
        public InputAction @Minimap => m_Wrapper.m_Player_Minimap;
        public InputAction @Escape => m_Wrapper.m_Player_Escape;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Sprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Interaction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteraction;
                @Drag.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrag;
                @Drag.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrag;
                @Drag.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrag;
                @Zoom.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoom;
                @Chat.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChat;
                @Chat.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChat;
                @Chat.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChat;
                @Shortcut1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut1;
                @Shortcut1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut1;
                @Shortcut1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut1;
                @Shortcut2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut2;
                @Shortcut2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut2;
                @Shortcut2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut2;
                @Shortcut3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut3;
                @Shortcut3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut3;
                @Shortcut3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut3;
                @Shortcut4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut4;
                @Shortcut4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut4;
                @Shortcut4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut4;
                @Shortcut5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut5;
                @Shortcut5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut5;
                @Shortcut5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut5;
                @Shortcut6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut6;
                @Shortcut6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut6;
                @Shortcut6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut6;
                @Shortcut7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut7;
                @Shortcut7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut7;
                @Shortcut7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut7;
                @Shortcut8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut8;
                @Shortcut8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut8;
                @Shortcut8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut8;
                @Shortcut9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut9;
                @Shortcut9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut9;
                @Shortcut9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut9;
                @Shortcut0.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut0;
                @Shortcut0.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut0;
                @Shortcut0.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShortcut0;
                @Emotion.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEmotion;
                @Emotion.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEmotion;
                @Emotion.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEmotion;
                @Ctrl.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCtrl;
                @Ctrl.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCtrl;
                @Ctrl.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCtrl;
                @Minimap.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMinimap;
                @Minimap.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMinimap;
                @Minimap.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMinimap;
                @Escape.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @Drag.started += instance.OnDrag;
                @Drag.performed += instance.OnDrag;
                @Drag.canceled += instance.OnDrag;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Chat.started += instance.OnChat;
                @Chat.performed += instance.OnChat;
                @Chat.canceled += instance.OnChat;
                @Shortcut1.started += instance.OnShortcut1;
                @Shortcut1.performed += instance.OnShortcut1;
                @Shortcut1.canceled += instance.OnShortcut1;
                @Shortcut2.started += instance.OnShortcut2;
                @Shortcut2.performed += instance.OnShortcut2;
                @Shortcut2.canceled += instance.OnShortcut2;
                @Shortcut3.started += instance.OnShortcut3;
                @Shortcut3.performed += instance.OnShortcut3;
                @Shortcut3.canceled += instance.OnShortcut3;
                @Shortcut4.started += instance.OnShortcut4;
                @Shortcut4.performed += instance.OnShortcut4;
                @Shortcut4.canceled += instance.OnShortcut4;
                @Shortcut5.started += instance.OnShortcut5;
                @Shortcut5.performed += instance.OnShortcut5;
                @Shortcut5.canceled += instance.OnShortcut5;
                @Shortcut6.started += instance.OnShortcut6;
                @Shortcut6.performed += instance.OnShortcut6;
                @Shortcut6.canceled += instance.OnShortcut6;
                @Shortcut7.started += instance.OnShortcut7;
                @Shortcut7.performed += instance.OnShortcut7;
                @Shortcut7.canceled += instance.OnShortcut7;
                @Shortcut8.started += instance.OnShortcut8;
                @Shortcut8.performed += instance.OnShortcut8;
                @Shortcut8.canceled += instance.OnShortcut8;
                @Shortcut9.started += instance.OnShortcut9;
                @Shortcut9.performed += instance.OnShortcut9;
                @Shortcut9.canceled += instance.OnShortcut9;
                @Shortcut0.started += instance.OnShortcut0;
                @Shortcut0.performed += instance.OnShortcut0;
                @Shortcut0.canceled += instance.OnShortcut0;
                @Emotion.started += instance.OnEmotion;
                @Emotion.performed += instance.OnEmotion;
                @Emotion.canceled += instance.OnEmotion;
                @Ctrl.started += instance.OnCtrl;
                @Ctrl.performed += instance.OnCtrl;
                @Ctrl.canceled += instance.OnCtrl;
                @Minimap.started += instance.OnMinimap;
                @Minimap.performed += instance.OnMinimap;
                @Minimap.canceled += instance.OnMinimap;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Confirm;
    private readonly InputAction m_UI_Zoom;
    private readonly InputAction m_UI_LeftDrag;
    private readonly InputAction m_UI_RightDrag;
    private readonly InputAction m_UI_Minimap;
    private readonly InputAction m_UI_Escape;
    public struct UIActions
    {
        private @Com2VerseAction m_Wrapper;
        public UIActions(@Com2VerseAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Confirm => m_Wrapper.m_UI_Confirm;
        public InputAction @Zoom => m_Wrapper.m_UI_Zoom;
        public InputAction @LeftDrag => m_Wrapper.m_UI_LeftDrag;
        public InputAction @RightDrag => m_Wrapper.m_UI_RightDrag;
        public InputAction @Minimap => m_Wrapper.m_UI_Minimap;
        public InputAction @Escape => m_Wrapper.m_UI_Escape;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Confirm.started -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Zoom.started -= m_Wrapper.m_UIActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnZoom;
                @LeftDrag.started -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftDrag;
                @LeftDrag.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftDrag;
                @LeftDrag.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftDrag;
                @RightDrag.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightDrag;
                @RightDrag.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightDrag;
                @RightDrag.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightDrag;
                @Minimap.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimap;
                @Minimap.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimap;
                @Minimap.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimap;
                @Escape.started -= m_Wrapper.m_UIActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @LeftDrag.started += instance.OnLeftDrag;
                @LeftDrag.performed += instance.OnLeftDrag;
                @LeftDrag.canceled += instance.OnLeftDrag;
                @RightDrag.started += instance.OnRightDrag;
                @RightDrag.performed += instance.OnRightDrag;
                @RightDrag.canceled += instance.OnRightDrag;
                @Minimap.started += instance.OnMinimap;
                @Minimap.performed += instance.OnMinimap;
                @Minimap.canceled += instance.OnMinimap;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // WebViewUI
    private readonly InputActionMap m_WebViewUI;
    private IWebViewUIActions m_WebViewUIActionsCallbackInterface;
    private readonly InputAction m_WebViewUI_Confirm;
    public struct WebViewUIActions
    {
        private @Com2VerseAction m_Wrapper;
        public WebViewUIActions(@Com2VerseAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Confirm => m_Wrapper.m_WebViewUI_Confirm;
        public InputActionMap Get() { return m_Wrapper.m_WebViewUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WebViewUIActions set) { return set.Get(); }
        public void SetCallbacks(IWebViewUIActions instance)
        {
            if (m_Wrapper.m_WebViewUIActionsCallbackInterface != null)
            {
                @Confirm.started -= m_Wrapper.m_WebViewUIActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_WebViewUIActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_WebViewUIActionsCallbackInterface.OnConfirm;
            }
            m_Wrapper.m_WebViewUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
            }
        }
    }
    public WebViewUIActions @WebViewUI => new WebViewUIActions(this);

    // WaitingBlock
    private readonly InputActionMap m_WaitingBlock;
    private IWaitingBlockActions m_WaitingBlockActionsCallbackInterface;
    public struct WaitingBlockActions
    {
        private @Com2VerseAction m_Wrapper;
        public WaitingBlockActions(@Com2VerseAction wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_WaitingBlock; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WaitingBlockActions set) { return set.Get(); }
        public void SetCallbacks(IWaitingBlockActions instance)
        {
            if (m_Wrapper.m_WaitingBlockActionsCallbackInterface != null)
            {
            }
            m_Wrapper.m_WaitingBlockActionsCallbackInterface = instance;
            if (instance != null)
            {
            }
        }
    }
    public WaitingBlockActions @WaitingBlock => new WaitingBlockActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnDrag(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnChat(InputAction.CallbackContext context);
        void OnShortcut1(InputAction.CallbackContext context);
        void OnShortcut2(InputAction.CallbackContext context);
        void OnShortcut3(InputAction.CallbackContext context);
        void OnShortcut4(InputAction.CallbackContext context);
        void OnShortcut5(InputAction.CallbackContext context);
        void OnShortcut6(InputAction.CallbackContext context);
        void OnShortcut7(InputAction.CallbackContext context);
        void OnShortcut8(InputAction.CallbackContext context);
        void OnShortcut9(InputAction.CallbackContext context);
        void OnShortcut0(InputAction.CallbackContext context);
        void OnEmotion(InputAction.CallbackContext context);
        void OnCtrl(InputAction.CallbackContext context);
        void OnMinimap(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnConfirm(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnLeftDrag(InputAction.CallbackContext context);
        void OnRightDrag(InputAction.CallbackContext context);
        void OnMinimap(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IWebViewUIActions
    {
        void OnConfirm(InputAction.CallbackContext context);
    }
    public interface IWaitingBlockActions
    {
    }
}
