@ECHO OFF

SET "release_path=E:/Com2VERSE/graphic/Unity_work/Com2VERSE_Release/Com2VERSE_Release_20220913"

MKLINK /J "./com.com2verse.assetsystem" "%release_path%/Packages/com.com2verse.assetsystem"
MKLINK /J "./com.com2verse.avatar" "%release_path%/Packages/com.com2verse.avatar"
MKLINK /J "./com.com2verse.avataranimation" "%release_path%/Packages/com.com2verse.avataranimation"
MKLINK /J "./com.com2verse.bannedwords" "%release_path%/Packages/com.com2verse.bannedwords"
MKLINK /J "./com.com2verse.builder" "%release_path%/Packages/com.com2verse.builder"
MKLINK /J "./com.com2verse.buildhelper" "%release_path%/Packages/com.com2verse.buildhelper"
MKLINK /J "./com.com2verse.c2vapi" "%release_path%/Packages/com.com2verse.c2vapi"
MKLINK /J "./com.com2verse.camerasystem" "%release_path%/Packages/com.com2verse.camerasystem"
MKLINK /J "./com.com2verse.chat" "%release_path%/Packages/com.com2verse.chat"
MKLINK /J "./com.com2verse.communication" "%release_path%/Packages/com.com2verse.communication"
MKLINK /J "./com.com2verse.core" "%release_path%/Packages/com.com2verse.core"
MKLINK /J "./com.com2verse.dataloader" "%release_path%/Packages/com.com2verse.dataloader"
MKLINK /J "./com.com2verse.dll" "%release_path%/Packages/com.com2verse.dll"
MKLINK /J "./com.com2verse.event" "%release_path%/Packages/com.com2verse.event"
MKLINK /J "./com.com2verse.httphelper" "%release_path%/Packages/com.com2verse.httphelper"
MKLINK /J "./com.com2verse.input" "%release_path%/Packages/com.com2verse.input"
MKLINK /J "./com.com2verse.localcache" "%release_path%/Packages/com.com2verse.localcache"
MKLINK /J "./com.com2verse.localization" "%release_path%/Packages/com.com2verse.localization"
MKLINK /J "./com.com2verse.logger" "%release_path%/Packages/com.com2verse.logger"
MKLINK /J "./com.com2verse.mvvm" "%release_path%/Packages/com.com2verse.mvvm"
MKLINK /J "./com.com2verse.network" "%release_path%/Packages/com.com2verse.network"
MKLINK /J "./com.com2verse.notification" "%release_path%/Packages/com.com2verse.notification"
MKLINK /J "./com.com2verse.object" "%release_path%/Packages/com.com2verse.object"
MKLINK /J "./com.com2verse.organization" "%release_path%/Packages/com.com2verse.organization"
MKLINK /J "./com.com2verse.platformcontroller" "%release_path%/Packages/com.com2verse.platformcontroller"
MKLINK /J "./com.com2verse.qrcode" "%release_path%/Packages/com.com2verse.qrcode"
MKLINK /J "./com.com2verse.recyclablescroll" "%release_path%/Packages/com.com2verse.recyclablescroll"
MKLINK /J "./com.com2verse.rendertexture" "%release_path%/Packages/com.com2verse.rendertexture"
MKLINK /J "./com.com2verse.screenshare" "%release_path%/Packages/com.com2verse.screenshare"
MKLINK /J "./com.com2verse.soundsystem" "%release_path%/Packages/com.com2verse.soundsystem"
MKLINK /J "./com.com2verse.storageapi" "%release_path%/Packages/com.com2verse.storageapi"
MKLINK /J "./com.com2verse.texturecache" "%release_path%/Packages/com.com2verse.texturecache"
MKLINK /J "./com.com2verse.trie" "%release_path%/Packages/com.com2verse.trie"
MKLINK /J "./com.com2verse.tts" "%release_path%/Packages/com.com2verse.tts"
MKLINK /J "./com.com2verse.tweener" "%release_path%/Packages/com.com2verse.tweener"
MKLINK /J "./com.com2verse.unityassettool" "%release_path%/Packages/com.com2verse.unityassettool"
MKLINK /J "./com.com2verse.vuplex" "%release_path%/Packages/com.com2verse.vuplex"
MKLINK /J "./com.com2verse.websockethelper" "%release_path%/Packages/com.com2verse.websockethelper"
MKLINK /J "./com.com2verse.webview" "%release_path%/Packages/com.com2verse.webview"
MKLINK /J "./com.immersivevrtools.hotreload" "%release_path%/Packages/com.immersivevrtools.hotreload"

PAUSE